config/routes.rb
Rails.application.routes.draw do

  resources :staffers
  resources :bills
  resources :voters

  root 'staffers#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :staffer
  has_many :votes

  validates :name, presence: true, uniqueness: true

  def percent_yes
    count = 0.0
    votes.each do |v|
      count += 1 if v.yes_or_no
    end
    (count / votes.length ) * 100
  end
end

app/models/staffer.rb
class Staffer < ActiveRecord::Base
  has_secure_password
  has_many :bills

  validates :email, presence: true, uniqueness: true

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :bill
  belongs_to :voter
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]


  def index
    @bills = Bill.all
  end

  def new
    @bill = Bill.new
  end

  def show
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to root_path, notice: 'Bill was successfully created.'
    else
      render :new
    end
  end

  def update
    if @bill.update(bill_params)
      redirect_to root_path, notice: 'Bill was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @bill.destroy
      redirect_to bills_url, notice: 'Bill was successfully destroyed.'
  end

  private
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def bill_params
      params.require(:bill).permit(:name, :description, :staffer_id)
    end
end

app/controllers/staffers_controller.rb
class StaffersController < ApplicationController
  before_action :set_staffer, only: [:show, :edit, :update, :destroy]

  def index
    @staffers = Staffer.all
  end

  def new
    @staffer = Staffer.new
  end

  def show
  end

  def edit
  end

  def create
    @staffer = Staffer.new(staffer_params)
    if @staffer.save
      redirect_to root_path, notice: 'Staffer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @staffer.update(staffer_params)
      redirect_to root_path, notice: 'Staffer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @staffer.destroy
      redirect_to staffer_url, notice: 'Staffer was successfully destroyed.'
  end

  private
    def set_staffer
      @staffer = Staffer.find(params[:id])
    end

    def staffer_params
      params.require(:staffer).permit(:name, :email, :password)
    end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  before_action :set_voter, only: [:show, :edit, :update, :destroy]

  def index
    @voters = Voter.all
  end

  def new
    @voter = Voter.new
  end

  def show
  end

  def edit
  end

  def create
    @voter = Voter.new(voter_params)
    if @voter.save
      redirect_to root_path, notice: 'Voter was successfully created.'
    else
      render :new
    end
  end

  def update
    if @voter.update(voter_params)
      redirect_to root_path, notice: 'Voter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @voter.destroy
      redirect_to voter_url, notice: 'Voter was successfully destroyed.'
  end

  private
    def set_voter
      @voter = Voter.find(params[:id])
    end

    def voter_params
      params.require(:voter).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/staffers_helper.rb
module StaffersHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/bills/create.html.erb
<h1>Bills#create</h1>
<p>Find me in app/views/bills/create.html.erb</p>

app/views/bills/destroy.html.erb
<h1>Bills#destroy</h1>
<p>Find me in app/views/bills/destroy.html.erb</p>

app/views/bills/edit.html.erb
<h1>Bills#edit</h1>
<p>Find me in app/views/bills/edit.html.erb</p>

app/views/bills/index.html.erb
<h1>Bills#index</h1>
<p>Find me in app/views/bills/index.html.erb</p>

app/views/bills/new.html.erb
<h1>Bills#new</h1>
<p>Find me in app/views/bills/new.html.erb</p>

app/views/bills/show.html.erb
<h1>Bills#show</h1>
<p>Find me in app/views/bills/show.html.erb</p>

app/views/bills/update.html.erb
<h1>Bills#update</h1>
<p>Find me in app/views/bills/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrazyVote</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/staffers/create.html.erb
<h1>Staffers#create</h1>
<p>Find me in app/views/staffers/create.html.erb</p>

app/views/staffers/destroy.html.erb
<h1>Staffers#destroy</h1>
<p>Find me in app/views/staffers/destroy.html.erb</p>

app/views/staffers/edit.html.erb
<h1>Staffers#edit</h1>
<p>Find me in app/views/staffers/edit.html.erb</p>

app/views/staffers/index.html.erb
<h1>Staffers#index</h1>
<p>Find me in app/views/staffers/index.html.erb</p>
<h1>Bills</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffers.each do |s| %>
      <% s.bills.each do |b| %>
        <tr>
          <td><%= s.name %></td>
          <td><%= s.email %></td>
          <td><%= link_to 'Edit', edit_staffer_path(s) %></td>
          <td><%= link_to 'Delete', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <tr>
          <td><%= b.name %></td>
          <td><%= b.description %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Bill', new_bill_path %>

app/views/staffers/new.html.erb
<h1>Staffers#new</h1>
<p>Find me in app/views/staffers/new.html.erb</p>

app/views/staffers/show.html.erb
<h1>Staffers#show</h1>
<p>Find me in app/views/staffers/show.html.erb</p>

app/views/staffers/update.html.erb
<h1>Staffers#update</h1>
<p>Find me in app/views/staffers/update.html.erb</p>

app/views/voters/create.html.erb
<h1>Voters#create</h1>
<p>Find me in app/views/voters/create.html.erb</p>

app/views/voters/destroy.html.erb
<h1>Voters#destroy</h1>
<p>Find me in app/views/voters/destroy.html.erb</p>

app/views/voters/edit.html.erb
<h1>Voters#edit</h1>
<p>Find me in app/views/voters/edit.html.erb</p>

app/views/voters/index.html.erb
<h1>Voters#index</h1>
<p>Find me in app/views/voters/index.html.erb</p>

app/views/voters/new.html.erb
<h1>Voters#new</h1>
<p>Find me in app/views/voters/new.html.erb</p>

app/views/voters/show.html.erb
<h1>Voters#show</h1>
<p>Find me in app/views/voters/show.html.erb</p>

app/views/voters/update.html.erb
<h1>Voters#update</h1>
<p>Find me in app/views/voters/update.html.erb</p>